Phantom.MVC/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phantom.MVC.Models;
using Phantom.Logic;
using Phantom.Core;
namespace Phantom.MVC.Controllers
{
    public class BranchController : Controller
    {
        Repository<Branch> repository = new Repository<Branch>();
        //
        // GET: /Branch/
        public ActionResult Index()
        {
            List<Branch> branches = repository.GetAll();           
            return View(branches);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Branch branch)
        {
            if (ModelState.IsValid)
            {
                repository.Insert(branch);
                CommitTransactions.CommitAll();
                TempData["message"] = "Successfully created Branch";             
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Test/Edit/5
        public ActionResult Edit(int id)
        {
            Branch branch = repository.GetByID(id);
            //BranchModel test = branch as BranchModel;
            if (branch == null)
            {
                TempData["message"] = "Branch not found!";      
                return RedirectToAction("Index");
            }
    
            return View(branch);
        }
        // POST: /Test/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            Branch branch = repository.GetByID(id);
            if (branch == null)
            {
                TempData["message"] = "Branch not found!";
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                UpdateModel(branch);
                repository.Update(branch);
                CommitTransactions.CommitAll();
                TempData["message"] = "Successfully updated Branch";
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Details(int id)
        {
            Branch branch = repository.GetByID(id);
            if (branch == null)
            {
                TempData["message"] = "Branch not found!";
                return RedirectToAction("Index");
            }

            return View(branch);
        }

    }
}

Phantom.MVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phantom.Logic;
using Phantom.Core;
using Phantom.MVC.Models;

namespace Phantom.MVC.Controllers
{
    public class CustomerController : Controller
    {
        Repository<Customer> repository = new Repository<Customer>();
        //
        // GET: /Customer/
        public ActionResult Index()
        {
            List<Customer> customers = repository.GetAll();
            return View(customers);
        }

        //
        // GET: /Customer/Details/5
        public ActionResult Details(int id)
        {
            Customer customer = repository.GetByID(id);
            if (customer == null)
            {
                TempData["message"] = "Customer not found!";
                return RedirectToAction("Index");
            }
           
            return View(customer);
        }

        //
        // GET: /Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Customer/Create
        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {               
                repository.Insert(customer);
                CommitTransactions.CommitAll();
                TempData["message"] = "Successfully created Customer";
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Customer/Edit/5
        public ActionResult Edit(int id)
        {
            Customer customer = repository.GetByID(id);
            if (customer == null)
            {
                TempData["message"] = "Customer not found!";
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        //
        // POST: /Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            Customer customer = repository.GetByID(id);
            if (customer == null)
            {
                TempData["message"] = "Customer not found!";
                return RedirectToAction("Index");
            }
            
            if (ModelState.IsValid)
            {
                UpdateModel(customer);
                repository.Update(customer);
                CommitTransactions.CommitAll();
                TempData["message"] = "Successfully updated Branch";
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Customer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Phantom.MVC/Controllers/GLCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phantom.Logic;
using Phantom.Core;
using Phantom.MVC.Models;

namespace Phantom.MVC.Controllers
{
    public class GLCategoryController : Controller
    {
        Repository<GLCategory> repository = new Repository<GLCategory>();
        GLCategory category;
        //
        // GET: /GLCategory/
        public ActionResult Index()
        {
            List<GLCategory> categories = repository.GetAll();
            return View(categories);
        }

        //
        // GET: /GLCategory/Details/5
        public ActionResult Details(int id)
        {
            category = repository.GetByID(id);
            if (category == null)
            {
                TempData["message"] = "Category not found!";
                return RedirectToAction("Index");
            }

            return View(category);
        }

        //
        // GET: /GLCategory/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /GLCategory/Create
        [HttpPost]
        public ActionResult Create(GLCategory glCategory)
        {

            if (ModelState.IsValid)
            {               
                repository.Insert(glCategory);
                CommitTransactions.CommitAll();
                TempData["message"] = "Successfully created GL Category";
                return RedirectToAction("Index");
            }
            return View();

        }

        //
        // GET: /GLCategory/Edit/5
        public ActionResult Edit(int id)
        {
            category = repository.GetByID(id);
            if (category == null)
            {
                TempData["message"] = "GL Category not found";
                return RedirectToAction("Index");
            }

            return View(category);

        }

        //
        // POST: /GLCategory/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                category = repository.GetByID(id);
                if (category == null)
                {
                    TempData["message"] = "Category not found!";
                    return RedirectToAction("Index");
                }

                if (ModelState.IsValid)
                {
                    UpdateModel(category);
                    repository.Update(category);
                    CommitTransactions.CommitAll();
                    TempData["message"] = "Successfully updated GL Category";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /GLCategory/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /GLCategory/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Phantom.MVC/Controllers/NuggetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phantom.Logic;
using Phantom.Core;
using Phantom.MVC.Models;

namespace Phantom.MVC.Controllers
{
    public class NuggetController : Controller
    {
        NuggetLogic logic = new NuggetLogic();
        //
        // GET: /Nugget/
        [ChildActionOnly]
        public ActionResult GetNugget()
        {
            Nugget nugget = logic.GetRandomNugget();      

            return PartialView("_Nugget",nugget);
        }
	}
}

Phantom.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("tablestunts", required: false)
    @RenderSection("demojs", required: false)

    
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="../../assets/css/themify-icons.css" rel="stylesheet">
</head>
<body>
  
    <div class="wrapper">
        <div class="sidebar" data-background-color="white" data-active-color="warning">
            <!--
                Tip 1: you can change the color of the sidebar's background using: data-background-color="white | brown"
                Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
            -->
            <div class="logo">
                <a href="../../../www_creative-tim_default.html" class="simple-text">
                    Phantom 2.0
                </a>
            </div>
            <div class="logo logo-mini">
                <a href="../../../www_creative-tim_default.html" class="simple-text">
                    CT
                </a>
            </div>
            <div class="sidebar-wrapper">
               <ul class="nav">
                    <li>
                        <a  href="#">
                            <i class="ti-panel"></i>
                            <p>
                                Dashboard
                               
                            </p>
                        </a>                       
                    </li>
                    <li>
                        <a data-toggle="collapse" href="#branchLinks">
                            <i class="ti-package"></i>
                            <p>
                                 Branches
                                <b class="caret"></b>
                            </p>
                        </a>
                        <div class="collapse" id="branchLinks">
                            <ul class="nav">                               
                                <li>@Html.ActionLink("Create Branch", "Create", "Branch")</li>
                                <li>@Html.ActionLink("View Branches", "Index", "Branch")</li>                                
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a data-toggle="collapse" href="#customerLinks" >
                            <i class="ti-clipboard"></i>
                            <p>
                                Customers
                                <b class="caret"></b>
                            </p>
                        </a>
                        <div class="collapse in" id="customerLinks">
                            <ul class="nav">
                                <li>@Html.ActionLink("Create Customer", "Create", "Customer")</li>
                                <li>@Html.ActionLink("View Customers", "Index", "Customer")</li>   
                            </ul>
                        </div>
                    </li>
                   <li>
                       <a data-toggle="collapse" href="#glCategoryLinks">
                           <i class="ti-clipboard"></i>
                           <p>
                               GL Categories
                               <b class="caret"></b>
                           </p>
                       </a>
                       <div class="collapse in" id="glCategoryLinks">
                           <ul class="nav">
                               <li>@Html.ActionLink("Create Category", "Create", "GLCategory")</li>
                               <li>@Html.ActionLink("View Categories", "Index", "GLCategory")</li>
                           </ul>
                       </div>
                   </li>
                    <li>
                        <a data-toggle="collapse" href="#">
                            <i class="ti-map"></i>
                            <p>
                                Maps
                                <b class="caret"></b>
                            </p>
                        </a>
                        <div class="collapse" id="mapsExamples">
                            <ul class="nav">
                               
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a href="#">
                            <i class="ti-bar-chart-alt"></i>
                            <p>Charts</p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="ti-calendar"></i>
                            <p>Calendar</p>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="collapse" href="#">
                            <i class="ti-gift"></i>
                            <p>
                                Pages
                                <b class="caret"></b>
                            </p>
                        </a>
                        <div class="collapse" id="#">
                            <ul class="nav">
                               
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                       <a class="navbar-brand" href="#">@ViewBag.Title</a>
                    </div>
                    <div class="collapse navbar-collapse">
                       <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="regular.html#stats" class="dropdown-toggle btn-magnify" data-toggle="dropdown">
                                    <i class="ti-panel"></i>
                                    <p>Stats</p>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="regular.html#notifications" class="dropdown-toggle btn-rotate" data-toggle="dropdown">
                                    <i class="ti-bell"></i>
                                    <span class="notification">5</span>
                                    <p class="hidden-md hidden-lg">
                                        Notifications
                                        <b class="caret"></b>
                                    </p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Notification 1</a></li>
                                    <li><a href="#">Notification 2</a></li>
                                    <li><a href="#">Notification 3</a></li>
                                    <li><a href="#">Notification 4</a></li>
                                    <li><a href="#">Another notification</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="regular.html#settings" class="btn-rotate">
                                    <i class="ti-settings"></i>
                                    <p class="hidden-md hidden-lg">
                                        Settings
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                      
                        @RenderBody()

                                             
                    </div> <!-- end row -->
                </div>

                <footer class="footer">
                    <div class="container-fluid">
                        <nav class="pull-left">
                            <ul>

                                <li>
                                    <a href="#">
                                        Seun Fapohunda
                                    </a>
                                </li>

                                <li>
                                    <a href="#">
                                        SkyFarm
                                    </a>
                                </li>
                                
                            </ul>
                        </nav>
                        <div class="copyright pull-right">
                            &copy;
                            <script>document.write(new Date().getFullYear())</script>, made with <i class="fa fa-heart heart"></i> by <a href="../../../www_creative-tim_default.html">Seun Fapohunda, for SkyFarm</a>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>

   
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    @*<script src="https://code.jquery.com/jquery.js"></script>*@
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    @* <script src="bootstrap/js/bootstrap.min.js"></script>*@
    @*<script src="js/custom.js"></script>*@
  
    @RenderSection("scripts", required: false)

    
</body>
</html>

Phantom.MVC/Views/Shared/_Nugget.cshtml
@model Phantom.Core.Nugget
<div class="col-md-6">
    <div class="card">

        <div class="header">
         <h4 class="title">Nuggets #@Model.Number</h4>
        </div>
        <div class="content">
            <p>
                 @Model.Tip
            </p>

        </div>

    </div> <!-- end card -->
</div> <!--  end col-md-6  -->