Phantom.MVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phantom.Logic;
using Phantom.Core;
using Phantom.MVC.Models;

namespace Phantom.MVC.Controllers
{
    public class CustomerController : Controller
    {
        Repository<Customer> repository = new Repository<Customer>();
        //
        // GET: /Customer/
        public ActionResult Index()
        {
            List<Customer> customers = repository.GetAll();
            return View(customers);
        }

        //
        // GET: /Customer/Details/5
        public ActionResult Details(int id)
        {
            Customer customer = repository.GetByID(id);
            if (customer == null)
            {
                TempData["message"] = "Customer not found!";
                return RedirectToAction("Index");
            }
           
            return View(customer);
        }

        //
        // GET: /Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Customer/Create
        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {               
                repository.Insert(customer);
                CommitTransactions.CommitAll();
                TempData["message"] = "Successfully created Customer";
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Customer/Edit/5
        public ActionResult Edit(int id)
        {
            Customer customer = repository.GetByID(id);
            if (customer == null)
            {
                TempData["message"] = "Customer not found!";
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        //
        // POST: /Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            Customer customer = repository.GetByID(id);
            if (customer == null)
            {
                TempData["message"] = "Customer not found!";
                return RedirectToAction("Index");
            }
            
            if (ModelState.IsValid)
            {
                UpdateModel(customer);
                repository.Update(customer);
                CommitTransactions.CommitAll();
                TempData["message"] = "Successfully updated Branch";
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Customer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Phantom.MVC/Controllers/NuggetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phantom.Logic;
using Phantom.Core;
using Phantom.MVC.Models;

namespace Phantom.MVC.Controllers
{
    public class NuggetController : Controller
    {
        NuggetLogic logic = new NuggetLogic();
        //
        // GET: /Nugget/
        [ChildActionOnly]
        public ActionResult GetNugget()
        {
            Nugget nugget = logic.GetRandomNugget();      

            return PartialView("_Nugget",nugget);
        }
	}
}

Phantom.MVC/Views/Customer/Create.cshtml
@model Phantom.Core.Customer
@{
    ViewBag.Title = "Customer Management";
}

@Html.AntiForgeryToken()

<div class="col-md-6">
    <div class="card">
        @*<form class="form-horizontal">*@
        @using (Html.BeginForm("Create", "Customer", FormMethod.Post,
 new { @class = "form-horizontal" }))
        {
            <div class="header">
                <h4 class="title">Create Customer</h4>
            </div>
            <div class="content">
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter First Name" }, })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Surname, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Last Name" }, })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Email" }, })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Phone Number" }, })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EnumDropDownListFor(model => model.Gender, new { @class = "selectpicker", data_title = "Select Gender", data_style = "btn-danger btn-block", data_menu_style = "dropdown-blue" })
                    </div>
                </div>

            </div>
            <div class="card-footer" style="margin-top:60px;">
                <div class="form-group">
                    <label class="col-md-3"></label>
                    <div class="col-md-9">
                        <button type="submit" class="btn btn-fill btn-info">
                            Create
                        </button>
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-fill btn-info" })
                    </div>
                </div>
            </div>
        }
        @*</form>*@
    </div> <!-- end card -->
</div> <!--  end col-md-6  -->
@*@Html.Partial("_Nugget");*@
@{Html.RenderAction("GetNugget", "Nugget");}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Phantom.MVC/Views/Customer/Details.cshtml
@model Phantom.Core.Customer
@{
    ViewBag.Title = "Customer Management";
}

<div class="col-md-6">
    <div class="card">
        <div class="header">
            <h4 class="title">Customer Details</h4>
        </div>
        <div class="content">
            <div class="typo-line">
                <h5>
                    <p class="category">@Html.DisplayNameFor(model => model.FirstName) :</p>
                </h5>
                @Html.DisplayFor(model => model.FirstName)
            </div>
            <div class="typo-line">
                <h5>
                    <p class="category">@Html.DisplayNameFor(model => model.Surname) :</p>
                </h5>
                @Html.DisplayFor(model => model.Surname)
            </div>
            <div class="typo-line">
                <h5>
                    <p class="category">@Html.DisplayNameFor(model => model.Email) :</p>
                </h5>
                @Html.DisplayFor(model => model.Email)
            </div>

            <div class="typo-line">
                <h5>
                    <p class="category">@Html.DisplayNameFor(model => model.Phone) :</p>
                </h5>
                @Html.DisplayFor(model => model.Phone)
            </div>

            <div class="typo-line">
                <h5>
                    <p class="category">@Html.DisplayNameFor(model => model.Gender) :</p>
                </h5>
                @Html.DisplayFor(model => model.Gender)
            </div>

            <div class="text-center">
                @Html.ActionLink("Update", "Edit", new { id = Model.Id }, new { @class = "btn btn-fill btn-info" })
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-fill btn-info" })
            </div>
            <div class="clearfix"></div>
        </div>


    </div> <!-- end card -->
</div> <!--  end col-md-6  -->
@*@Html.Partial("_Nugget");*@
@{Html.RenderAction("GetNugget", "Nugget");}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Phantom.MVC/Views/Customer/Edit.cshtml
@model Phantom.Core.Customer
@{
    ViewBag.Title = "Customer Management";
}
@Html.AntiForgeryToken()

<div class="col-md-6">
    <div class="card">
        @*<form class="form-horizontal">*@
        @using (Html.BeginForm("Edit", "Customer", FormMethod.Post,
 new { @class = "form-horizontal" }))
        {
            <div class="header">
                <h4 class="title">Update Customer</h4>
            </div>
            <div class="content">
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Name" }, })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Surname, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Name" }, })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Name" }, })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Name" }, })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.EnumDropDownListFor(model => model.Gender, new { @class = "selectpicker", data_title = "Select Status", data_style = "btn-danger btn-block", data_menu_style = "dropdown-blue" })
                    </div>
                </div>

            </div>
            <div class="card-footer" style="margin-top:60px;">
                <div class="form-group">
                    <label class="col-md-3"></label>
                    <div class="col-md-9">
                        <button type="submit" class="btn btn-fill btn-info">
                            Update
                        </button>
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-fill btn-info" })
                    </div>
                </div>
            </div>
        }
        @*</form>*@
    </div> <!-- end card -->
</div> <!--  end col-md-6  -->
@*@Html.Partial("_Nugget");*@
@{Html.RenderAction("GetNugget", "Nugget");}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Phantom.MVC/Views/Customer/Index.cshtml
@model IEnumerable<Phantom.Core.Customer>

@{
    ViewBag.Title = "Customer Management";
}
@{
    if (TempData["message"] != null)
    {
        <script type="text/javascript">
            demo.showNotification('top', 'center');           
        </script>
    }
}
<div class="col-md-12">
    <div class="card">
        <div class="row">
            <div class="col-md-3">
                <div class="header">
                    <h4 class="title">Customers</h4>

                </div>
            </div>
            <div class="col-md-2 col-md-offset-7" style="margin-top:15px">
                @Html.ActionLink("Create New", "Create", "Customer",null, new { @class = "btn btn-fill btn-info" });
            </div>


        </div>

        <div class="content">
            <div class="toolbar">
                <!--Here you can write extra buttons/actions for the toolbar-->

            </div>

            <div class="fresh-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.FirstName)</th>
                            <th>@Html.DisplayNameFor(model => model.Surname)</th>
                            <th>@Html.DisplayNameFor(model => model.Email)</th>
                            <th>@Html.DisplayNameFor(model => model.Phone)</th>
                            <th>@Html.DisplayNameFor(model => model.Gender)</th>
                            <th class="disabled-sorting">Actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.FirstName)</th>
                            <th>@Html.DisplayNameFor(model => model.Surname)</th>
                            <th>@Html.DisplayNameFor(model => model.Email)</th>
                            <th>@Html.DisplayNameFor(model => model.Phone)</th>
                            <th>@Html.DisplayNameFor(model => model.Gender)</th>
                            <th class="disabled-sorting">Actions</th>
                            
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
                                <td>@Html.DisplayFor(modelItem => item.Surname)</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                <td>@Html.DisplayFor(modelItem => item.Phone)</td>
                                <td>@Html.DisplayFor(modelItem => item.Gender)</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, null) |
                                    @Html.ActionLink("Details", "Details", new { id = item.Id }, null)
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>
            </div>

        </div>


    </div> <!-- end card -->
</div>
@section TableStunts{
    @Scripts.Render("~/bundles/TableMagic")
}
@section DemoJS{
    @Scripts.Render("~/bundles/DemoJS")
}